import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Appbar from "@/components/Frame/Appbar";
import Sidebar from "@/components/Frame/Sidebar";
import {Toaster} from "react-hot-toast";
import {cookies} from "next/headers";
import {redirect} from "next/navigation";
import _ from "lodash";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  const result = await fetch(`${process.env.NEXT_PUBLIC_FRONTEND_HOST}/api/user/me`, {
    method: "GET",
    next: { revalidate: 60 },
    headers: {
      'Authorization': `Bearer ${cookieStore.get('token')?.value}`
    }
  })

  if(!result.ok) {
    redirect("/dang-nhap")
  }

  const {user} = await result.json();

  const isAdmin = _.some(user.activeRoles || [], ["name", "ADMIN"])
  if(!isAdmin) {
    redirect("/dang-nhap")
  }
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <div className="min-h-screen bg-gray-50">
        <Appbar user={user} />
        <Sidebar />
        <main className="pt-16 min-h-screen">
          {children}
          <Toaster position="top-right" />
        </main>
      </div>
    </body>
    </html>
);
}
